Add PrestashopBaseImporter
That might contains utilities for the importers such as
'_import_dependency'. It is used for ManufacturerProductDependency,
which means we can get unit_for(PrestashopImporter,
'prestashop.product.template') and
unit_for(ManufacturerProductDependency, 'prestashop.product.template')
without getting an error:

AssertionError: Several classes found for <class
'openerp.addons.connector_prestashop.unit.importer.PrestashopImporter'>
with session <Session db_name: openerp_test, uid: 1, context: {}>, model
name: prestashop.product.template. Found: set([<class
'openerp.addons.connector_prestashop.models.product_template.importer.ManufacturerProductDependency'>,
<class
'openerp.addons.connector_prestashop.models.product_template.importer.ProductTemplateImporter'>])